### ISSUE TITLE
Possible bug during upgrading of website_sale_checkout_store git pulled on 20160922

### ISSUE THREAD

**Issue by pvanthony** [it-projects-llc/website-addons#111]
Here is the error when upgrading to the latest version of website_sale_checkout_store git pulled on 20160922 

-------------- start -----------------------
2016-09-22 18:15:40,138 4931 INFO online_booking openerp.modules.module: module website_sale_checkout_store: creating or updating database tables
2016-09-22 18:15:40,202 4931 INFO online_booking openerp.modules.loading: loading website_sale_checkout_store/templates.xml
2016-09-22 18:15:40,270 4931 INFO online_booking openerp.modules.loading: loading website_sale_checkout_store/views.xml
2016-09-22 18:15:40,289 4931 INFO online_booking openerp.modules.loading: loading website_sale_checkout_store/data/data.xml
2016-09-22 18:15:40,293 4931 ERROR online_booking openerp.sql_db: bad query: INSERT INTO "ir_config_parameter" ("id", "value", "key", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('ir_config_parameter_id_seq'), 'True', 'website_sale_checkout_store.nobill_noship', 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
Traceback (most recent call last):
  File "/opt/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: duplicate key value violates unique constraint "ir_config_parameter_key_uniq"
DETAIL:  Key (key)=(website_sale_checkout_store.nobill_noship) already exists.

2016-09-22 18:15:40,294 4931 CRITICAL online_booking openerp.service.server: Failed to initialize database `online_booking`.
Traceback (most recent call last):
  File "/opt/odoo/openerp/service/server.py", line 929, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/opt/odoo/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 351, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/openerp/tools/convert.py", line 900, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/openerp/tools/convert.py", line 986, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/openerp/tools/convert.py", line 852, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/opt/odoo/openerp/tools/convert.py", line 762, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_model.py", line 1065, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 372, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 4093, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 508, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/opt/odoo/openerp/models.py", line 4231, in _create
    tuple([u[2] for u in updates if len(u) > 2])
  File "/opt/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ParseError: "duplicate key value violates unique constraint "ir_config_parameter_key_uniq"
DETAIL:  Key (key)=(website_sale_checkout_store.nobill_noship) already exists.
" while parsing /opt/odoo/addons_other/yelizariev/website-addons/website_sale_checkout_store/data/data.xml:4, near
<record id="config_nobill_noship" model="ir.config_parameter">
            <field name="key">website_sale_checkout_store.nobill_noship</field>
            <field name="value">True</field>
        </record>

--------------- end -----------------------

**Comment by yelizariev** [comment]
The error means, that you already have parameter ``website_sale_checkout_store.nobill_noship`` (probably, created by you). You can update data.xml or remove the parameter before updating module
