### ISSUE TITLE
[website_sale_add_to_cart] Error when I write the amount as number

### ISSUE THREAD

**Issue by antoniocanovas** [it-projects-llc/website-addons#8]
Hi Ivan, and congratulations.
In this module the edition of the amount of products is allowed with the numeric keyboard.
If you press enter after change the number, you get:
Error message:
cart_update() takes at least 2 arguments (1 given).

**Comment by yelizariev** [comment]
I'll test it. Wait for updates

**Comment by yelizariev** [comment]
I cannot reproduce the issue.
But I found that when I press enter I am redirected to shop cart and product number is a number I typed plus 1.

**Comment by konerycloud** [comment]
I am working with mac updated, and chrome v44.
This is the error  (cart_update() takes at least 2 arguments (1 given)) , in the last step I press "Enter" :
https://drive.google.com/file/d/0B11FSt27LH8qUlhFY29TcXpFY1E/view?usp=sharing

**Comment by yelizariev** [comment]
Could you please repeat and when you get error click on "Traceback" section and then send me text

**Comment by konerycloud** [comment]
Traceback (most recent call last):
  File "/opt/openerp/odoo/addons/website/models/ir_http.py", line 199, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/opt/openerp/odoo/openerp/addons/base/ir/ir_http.py", line 147, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/openerp/odoo/openerp/http.py", line 666, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/openerp/odoo/openerp/addons/base/ir/ir_http.py", line 173, in _dispatch
    result = request.dispatch()
  File "/opt/openerp/odoo/openerp/http.py", line 684, in dispatch
    r = self._call_function(**self.params)
  File "/opt/openerp/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/openerp/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/openerp/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/openerp/odoo/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/opt/openerp/odoo/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
TypeError: cart_update() takes at least 2 arguments (1 given)

**Comment by yelizariev** [comment]
Traceback doesn't help.

Maybe you use some other custom module, that breaks cart_update
